[package]
name = "policy"
version = "0.1.0"
edition = "2021"
authors = ["Jamie Whiting"]

[dependencies]
datagen = { path = "../../datagen" }
monty = { path = "../../" }
goober = { git = 'https://github.com/jw1912/goober' }
montyformat = { git = 'https://github.com/jw1912/montyformat.git' }
